dist: xenial

language: python

branches:
  only:
    - master

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37,docs
    - python: 3.6
      env: TOXENV=py36

install:
  - ./.travis/install


script:
  - ./.travis/run tox

